### ISSUE TITLE
Make tables in What is CAA article easier to read

### ISSUE THREAD

**Issue by SarahCaminiti1** [dnsimple/dnsimple-support#604] opened 2020-08-03 15:32 UTC
<img width="755" alt="Screen Shot 2020-08-03 at 11 31 30 AM" src="https://user-images.githubusercontent.com/49121697/89199721-fa497300-d57c-11ea-96d0-bfc4fba65909.png">

<img width="702" alt="Screen Shot 2020-08-03 at 11 31 25 AM" src="https://user-images.githubusercontent.com/49121697/89199732-fcabcd00-d57c-11ea-9781-e83c9c2f2f9e.png">

Add color or something to make it easier to read

https://github.com/dnsimple/dnsimple-support/pull/595/files#diff-37720b22f501298d90e7fce61b4b3a87

**Comment by sbastn** [comment] 2020-08-04 06:55
Duplicate of #603

**Closed by sbastn** 2020-08-04 06:55 UTC
